### ISSUE TITLE
Please select fonts

### ISSUE THREAD

**Issue by suige** [Doiverson/The_Chocolate_Whip_Cream#7]
Please select fonts that use main font(sans) and heading font(sans-serif) from Google fonts.
https://fonts.google.com/

After that, please let me know.

**Comment by suusan11** [comment]
Serif: Mate
Sans-Serif: Avenir

**Comment by suige** [comment]
@suusan11 Thanks, but unfortunately Avenir doesn't exist in Google fonts.
Please select another one.

**Comment by suusan11** [comment]
Sans-Serif: Didact Gothic
